source .env
OUTPUT_LOC="$OUTPUT_DIR/test.out"
BUILD_SPECIFIC_FILES='./src/test_main.c ./src/test.c'

$COMPILER -DDEBUG_MODE -DTEST_MODE $WARNINGS $FLAGS $FILES $BUILD_SPECIFIC_FILES -o $OUTPUT_LOC && $OUTPUT_LOC $@
